import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="border-b bg-gradient-to-r from-blue-500 to-purple-700 text-white py-4">
         <h1 className="text-2xl font-bold flex justify-center">Navbar</h1>
        </nav>

        {children}
        </body>
    </html>
  );
}
